name: Build and Push (amd64 only)

on:
  push:
    branches: [ main ]
    tags: [ 'v*' ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

env:
  REGISTRY: ghcr.io
  IMAGE_PREFIX: ghcr.io/sifterstudios/nuotti

jobs:
  build-amd64:
    # Matches your Unraid runner labels from compose
    runs-on: [self-hosted, unraid, docker, amd64]
    permissions:
      contents: read
      packages: write

    strategy:
      matrix:
        include:
          - service: backend
            context: .
            dockerfile: Nuotti.Backend/Dockerfile
            image: backend
          - service: audience
            context: .
            dockerfile: Nuotti.Audience/Dockerfile
            image: audience
          - service: web
            context: web
            dockerfile: web/Dockerfile
            image: web

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
        with:
          install: true
          cleanup: false
          driver-opts: |
            image=moby/buildkit:v0.13.2

      - name: Login to GHCR
        if: github.event_name != 'pull_request'
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Extract metadata (tags/labels) with -amd64 suffix
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ${{ env.IMAGE_PREFIX }}-${{ matrix.image }}
          flavor: |
            suffix=-amd64,onlatest=false
          tags: |
            type=ref,event=branch
            type=ref,event=pr
            type=semver,pattern={{version}}
            type=semver,pattern={{major}}.{{minor}}
            type=semver,pattern={{major}}
            type=sha,prefix={{branch}}-
            type=raw,value=latest,enable={{is_default_branch}}

      - name: Build & push (native amd64)
        id: build
        uses: docker/build-push-action@v6
        with:
          context: ${{ matrix.context }}
          file: ${{ matrix.dockerfile }}
          push: ${{ github.event_name != 'pull_request' }}
          # native build → no platforms key
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          cache-from: type=local,src=/runner/_work/buildx-cache
          cache-to: type=local,dest=/runner/_work/buildx-cache,mode=max
