name: CI

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '9.0.x'
      - name: Restore
        run: dotnet restore Nuotti.sln
      - name: Build
        run: dotnet build Nuotti.sln --configuration Release --no-restore
      - name: Install Playwright CLI
        run: dotnet tool install --global Microsoft.Playwright.CLI
      - name: Install Playwright Browsers
        shell: pwsh
        run: |
          $env:Path += ";$env:USERPROFILE\.dotnet\tools"
          dotnet playwright install
      - name: Test
        env:
          PATH: ${{ env.PATH }};${{ runner.tool_cache }}\playwright\win32_x64;${{ runner.temp }}
        run: dotnet test Nuotti.sln --no-build --configuration Release --logger trx --collect:"XPlat Code Coverage"
