name: Build & Deploy (Unraid)

on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: [self-hosted, unraid, docker]
    timeout-minutes: 60

    steps:
      - uses: actions/checkout@v4

      - name: Docker info
        run: |
          docker version
          docker compose version

      - name: Build images
        run: docker compose -f deploy/docker-compose.yml build --pull

      - name: Deploy
        run: docker compose -f deploy/docker-compose.yml up -d --remove-orphans

      - name: Light prune
        run: docker image prune -f
